betagouv/mdph

- client/components/nav-steps/nav-steps.html
Lors de la 1ere question "vie quotidienne" etc.. le bouton question précédente est désactivé mais on pourrait le remplacer par un bouton "retour au profil"
> Bouton "Retour au profil"

- client/app/departement/departement.html
Pour les MDPH non encore ouvertes certaines sections ne sont pas utiles.
- Désactiver la partie 'Vous êtes médecin' et 'Vous êtes partenaire'
- Désactiver la partie 'En fonction de votre situation, vous pourrez peut-être bénéficier des droits suivants'
https://trello.com/c/E2XPWpYR/438-etq-usager-je-trouve-une-page-mdph-non-ouverte-simplifiee
> ETQ usager je trouve une page MDPH non ouverte simplifiée

- client/app/profil/identites/autorite.js
- client/app/profil/identites/autorites.html
- client/app/profil/identites/autre.html
- client/app/profil/identites/autre.js
- client/app/profil/identites/beneficiaire.html
- client/app/profil/identites/beneficiaire.js
- client/components/adresse.data.gouv/adresse.data.gouv.js
- client/components/autorite-form/autorite.component.js
- client/components/autorite-form/autorite.controller.js
- client/components/autorite-form/autorite.html
Le comportement actuel est différent sur chaque écran d'identité (bénéficiaire / autorité parentale / aidant / organisme).
Je reprend le comportement de l'écran bénéficiaire pour faire converger chaque écran:
- On ne demande plus la géolocalisation de chaque utilisateur (plus de popup)
- On utilise les coordonnées GPS de la MDPH pour affiner les résultats de recherche de la BAN
> ETQ utilisateur je ne suis pas sollicité sur ma géolocalisation

- client/app/dashboard/dispatch/dispatch.js
- client/app/dashboard/dispatch/regles/edit/edit.controller.js
- client/app/dashboard/dispatch/secteurs/edit/edit.controller.js
- client/components/resources/dispatch-rule.resource.js
- client/components/resources/secteur.resource.js
- server/api/dispatch-rule/index.js
- server/api/mdph/index.js
- server/api/secteur/index.js
- server/routes.js
Les écrans "Distribution des demandes" et "Gestion des secteurs" devraient encore être totalement fonctionnels.
On ne peut plus accéder aux écrans des autres MDPHs en changeant l'identifiant dans l'URL (ex: http://localhost:9000/mdph/test/dashboard/dispatch/regles -> http://localhost:9000/mdph/59/dashboard/dispatch/regles )
> ETQ agent, je n'ai pas accès à la configuration des autres MDPH

- client/app/evaluation/detail/evaluation.detail.controller.js
- client/app/evaluation/detail/evaluation.detail.html
- client/components/trajectoire/trajectoire.component.js
- client/components/trajectoire/trajectoire.controller.js
- client/components/trajectoire/trajectoire.controller.spec.js
- client/components/trajectoire/trajectoire.html
Ajouter cette fonctionnalité sur tous les champs cochables qui disposent de champs d’un niveau inférieur. 
Cette fonctionnalité doit permettre de cocher un champ sans cocher les titres en amonts.
> ETQ utilisateur de l'outil de soutien, je peux déplier les sections contenant les champs cochables à l’aide d’un signe « + »

- client/app/profil/projet_de_vie/vie_quotidienne/situation.js
**Constat :**
La question "Êtes-vous à la retraite" s'affiche uniquement quand l'utilisateur répond à la question "Vous recevez" et lorsque l'utilisateur a plus de 20 ans.
La question « Vous percevez une ou plusieurs des aides suivantes : » s'affiche uniquement si l'utilisateur répond "Oui" à la question "Êtes-vous à la retraite".
**Attendu :**
Si l'utilisateur ne fait aucun choix à la question "Vous recevez", la question "Êtes-vous à la retraite" doit s'afficher. 
Comme l'existant, la question s'affiche uniquement si l'utilisateur a plus de 20ans.
Comme l'existant, la question « Vous percevez une ou plusieurs des aides suivantes : » s'affiche uniquement si l'utilisateur répond "Oui" à la question "Êtes-vous à la retraite".
> [Lot3] n°15 ETQ Bénéficiaire : modifier la condition d'affichage de la question « Êtes-vous à la retraite » du questionnaire "Vie quotidienne"

- client/components/autorite-form/autorite.html
Constat :
Les champs "Date de naissance", et "Complément d'adresse" sont obligatoires.
Attendu :
Ces champs doivent passer facultatifs.
> [Lot3] n°24 ETQ Bénéficiaire : Rendre facultatifs des champs dans le questionnaire "Identité de l'autorité parentale"

- client/app/profil/identites/beneficiaire.js
- client/app/profil/profil.html
- client/components/profile/profile.service.js
Constat :
Le questionnaire "Identité de l'autorité parentale" s'affiche si la date de naissance saisie est inférieure à 20 ans.
Cela signifie 2 choses:
- Affichage Bloc : sur la page "Profil", le bloc "Identité de l'autorité parentale" s'affiche
- Affichage du questionnaire dans le Chainage : sur le questionnaire "Identité Bénéficiaire", au clic sur le bouton "Valider", le questionnaire "Identité de l'autorité parentale" s'affiche".
Enfin sur la page profil, s'il s'affiche, le bloc "Identité de l'autorité parentale" s'affiche entre "Identité bénéficiaire" et "Vie quotidienne".
Attendu:
Pour les affichages du Bloc et du questionnaire dans le Chainage, changer ce fonctionnement par :
- Si le champ "Si c’est votre enfant qui est concerné par la demande, indiquer son numéro de sécurité …
> [Lot3.2] n°02 ETQ Bénéficiaire : Affichages du bloc et chainage du questionnaire "Identité de l'autorité parentale"

- client/app/profil/identites/autorite.js
- client/app/profil/identites/beneficiaire.html
- client/app/profil/identites/beneficiaire.js
- client/app/profil/profil.html
- server/components/register-handlebars.js
- server/components/templates/identite.html
Constat:
Ce questionnaire ne s'affiche pas dans le chainage, et son affichage n'est pas conditionné. En effet, il s'affiche toujours.
Attendu:
Comme aujourd'hui, le bloc du questionnaire s'affiche, c'est son chainage qui va changer :
Si l'utilisateur a saisi "Oui" à la question "Êtes-vous aidé.e dans vos démarches auprès de la MDPH ?" dans le questionnaire "Identité bénéficiaire", alors le questionnaire "Identité de la personne vous aidant dans cette démarche" s'affiche dans le chainage.
Si l'utilisateur a saisi "Non", alors le questionnaire ne s'affiche pas dans le chainage.
Si le questionnaire s'affiche dans le chainage, il s'affiche :
1) Derrière le questionnaire "Identité de l'autorité parentale" si ce dernier s'affiche.
2) Derrière "Identité bénéficiaire" si le questionnaire …
> [Lot3.2] n°03 ETQ Bénéficiaire : Affichage du chainage du questionnaire "Identité de la personne vous aidant dans cette démarche"

- client/app/profil/identites/autorite.js
- client/app/profil/identites/beneficiaire.js
- Si l'utilisateur a saisi "Oui" à la question "Êtes-vous aidé.e dans vos démarches auprès de la MDPH ?" dans le questionnaire "Identité bénéficiaire", alors le questionnaire "Identité de la personne vous aidant dans cette démarche" s'affiche dans le chainage.
- Si le questionnaire s'affiche dans le chainage, il s'affiche :
1) Derrière le questionnaire "Identité de l'autorité parentale" si ce dernier s'affiche.
2) Derrière "Identité bénéficiaire" si le questionnaire "Identité de l'autorité parentale" ne s'affiche pas.
> [Lot3.2_bugfix1] n°03 ETQ Bénéficiaire : Affichage du chainage du questionnaire "Identité de la personne vous aidant dans cette démarche"

- client/app/profil/aidant/aidant.js
- client/app/profil/identites/autorite.js
- client/app/profil/identites/autre.js
- client/app/profil/identites/beneficiaire.js
constat :
si on saisiOui à la question « Bénéficiez-vous d’une mesure de protection ? » et non à la question "êtes-vous aidé.e dans vos démarches..." dans le questionnaire "Identité bénéficiaire"
alors on obtient le chaînage "identité de l'autorité parentale" --> "situations particulières" --> "Vie quotidienne"
--> Il manque le questionnaire "Identité du représentant légal"
> [Lot3.2_bugfix02] n°04 ETQ Bénéficiaire : Affichage du chainage du questionnaire "Identité du représentant légal"

- client/app/profil/identites/beneficiaire.html
- client/app/profil/identites/beneficiaire.js
- client/components/date-service/date.service.js
- client/components/profile/profile.service.js
Constat :
le champ "Si c’est votre enfant qui est concerné par la demande, indiquer son numéro de sécurité sociale" est facultatif
Attendu :
pour le champ "Si c’est votre enfant qui est concerné par la demande, indiquer son numéro de sécurité sociale":
Si la date de naissance est < 16 ans, le champ s'affiche et est obligatoire. Au clic sur le bouton "Valider", si le champ est vide, un message d'erreur doit s'afficher.
Si la date de naissance est 16 ans ≤ âge < 20 ans, le champ s'affiche est facultatif
Si la date de naissance est >= 20 ans, le champ ne s'affiche pas
> [Lot3.2_bugfix01] n°01 ETQ Bénéficiaire : Questionnaire "Identité bénéficiaire": évol champ "sécurité sociale"

- client/components/autorite-form/autorite.html
Constat : 
Le bouton "Valider" du formulaire "Identité de l'autorité parentale" est vert mais ne fonctionne pas au clic, tant que la date de naissance n'a pas été remplie.
Attendu : 
Même si la date de naissance n'est pas renseignée (car non obligatoire), le clic sur "Valider" fonctionne (enregistrement+page suivante)
> [Lot3.2_bugfix01] n°24 ETQ Bénéficiaire : Rendre facultatifs des champs dans le questionnaire "Identité de l'autorité parentale"

- client/app/profil/profil.html
Constat:
Le bloc "Représentant légal" est affiché sans conditions (dans tous les cas).
IL est obligatoire à la validation de la demande.
Attendu:
Son affichage doit être conditionné par la question "Bénéficiez-vous d'une mesure de protection ?" du formulaire "Identité bénéficiaire"
> [Lot 3.2] Bug intra-version : Il y a 2 champs date de naissance pour l'autorité parentale

- client/app/profil/projet_de_vie/vie_quotidienne/situation.js
- server/api/sections/sections.json
**Constat:**
Les questions affichées dans le questionnaire "Vie quotidienne" s'affichent en fonction de l'âge du bénéficiaire.
Pour 5 questions, les réponses disponibles sont différentes en fonction de l'âge.
Les questions suivantes s'affichent uniquement si le bénéficiaire a 20 ans et plus :
- "Vous vivez"
- "Où vivez-vous?"
- "Dans les 12 mois précédents votre demande, avez vous perçu"
- "Vous avez besoin d'aide dans votre vie quotidienne"
- "Vous avez besoin d'aide pour votre vie sociale"
Lorsque le bénéficiaire a moins de 20 ans, il s'affiche plutôt:
- "[Prénom] vit"
- "Où vit [Prénom]?"
- "[Prénom] reçoit les aides, ressources et/ou prestations suivantes"
- "[Prénom] a besoin d'aide dans sa vie quotidienne ?"
- "[Prénom] a besoin d'aide pour sa vie sociale ?"
**Attendu:**
Pour ces 5 …
> [Lot3.2_bugfix01] n°10 ETQ Bénéficiaire : afficher les 5 mêmes questions avec les réponses correspondantes dans le questionnaire "Vie quotidienne"

- client/app/profil/identites/representants.html
- client/components/representant-form/representant.component.js
- client/components/representant-form/representant.controller.js
- client/components/representant-form/representant.html
- server/components/recapitulatif.js
Suite à une anomalie remontée via Mantis #6959, la case à cocher 'Même adresse que le bénéficiaire' induit une répercussion de l'adresse dans le PDF CERFA, tel qui décrit dans la carte liée #6959,
KO pour "Représentant légal 2 (le cas échéant)"
constaté : "Représentant légal 2"
attendu : "Représentant légal 2 (le cas échéant)" 
=>
reseigner l'adresse des representants dans le cas ou même adresse choisie et changer le libellé de la colonne pour le deuxieme représentant légal
> [Lot3.2_bugfix03] n°26 ETQ Bénéficiaire : Création du bloc et du questionnaire "Identité du représentant légal"

- client/app/layout/layout.html
- client/app/layout/layout.scss
- client/components/footer/footer.scss
OK sur le fonctionnement, KO pour le visuel sur le footer:
Dans le footer, les 2 lignes sont en décalages et la deuxième ligne commence en dessous de l'icône
=>
corriger la mise en page des horaires sur deux lignes
> [Lot3.2_bugfix01] Mantis 6908 : ETQ administrateur je souhaite saisir plusieurs ligne d'horaire

- client/app/demande/demande.controller.js
- client/components/demande-category/demande-category.controller.js
- client/components/service/demande.service.js
ETQ usager dans la page de création d'une demande, tous les blocs sont grisés tant que l’usager n’a pas rempli les champs obligatoires du questionnaire « Identité du bénéficiaire »
Les boutons "Modifier" des blocs grisés ne sont pas cliquables
Gérer le message d'erreur :
Au clic sur "Envoyer la demande", le message d'erreur suivant s'affiche:
Vous n'avez pas fini de remplir la section "Bénéficiaire"
> [Lot 4] N°01 - Demande - Griser les blocs tant que le bloc beneficiare n'est pas rempli convenablement

- server/components/recapitulatif.js
Constats :
Dans Vie scolaire et étudiante, à la question "Est-il placé en internat?" la réponse "Oui" est affichée, puis la sous-réponse " 'true' " est affichée
Attendus :
Modifier la façon dont la réponse à la sous question s'affiche dans le CERFA par :
Si l'usager répond oui à la sous-question :
° Oui
° Les frais de séjour sont intégralement pris en charge par l'assurance maladie, l'Etat ou l'aide sociale
Si l'usager répond non à la sous-question :
° Oui
° Les frais de séjour ne sont pas intégralement pris en charge par l'assurance maladie, l'Etat ou l'aide sociale
Modifier "Ses" par "Les" dans la sous-question affichée dans le formulaire en ligne
> [Lot 3.2_qualifInternePasse2] Bug d'affichage des réponses dans le CERFA - Mantis 7029 - sous-réponse sur les frais de séjour en internat

- client/app/dashboard/workflow/list/list.controller.js
- client/app/dashboard/workflow/list/list.html
*EBE p.44, 52*
**Attendu : Adaptation du tableau de bord des demandes validées ou irrecevables**
La sélection de plusieurs demandes suivie d’un clic sur le bouton « Action » permet de les télécharger ou de les supprimer en masse. Actions proposées:
- **[fa-download] « Télécharger les demandes »**
- [fa-trash] « Supprimer les demandes validées téléchargées » *=> Cf. carte 20*
**L’exécution de l’action de masse « télécharger » **
- Télécharge les demandes sémectionnées
- **Fait apparaître** le bouton **[fa-trash] « Supprimer »** *(pour les demandes cochées)*
*NB : Action existante, il faut ajouter l'appel à la fonction*
> [Lot 4] N°21 - Tableau de bord - Telecharger en masse

- client/app/dashboard/workflow/detail/detail.html
- client/app/dashboard/workflow/detail/modalDelete.html
- client/app/dashboard/workflow/list/list.controller.js
- client/app/dashboard/workflow/list/list.html
- client/app/dashboard/workflow/workflow.controller.js
La sélection de plusieurs demandes suivie d’un clic sur le bouton « Action » permet de les télécharger ou de les supprimer en masse. Actions proposées:
- [fa-download] « Télécharger les demandes » => *Cf carte 21*
- **[fa-trash] « Supprimer les demandes validées téléchargées »**
**L’exécution de l’action de masse « Supprimer » **
**Cas 1 :** Toutes les demandes sélectionnées ont déjà été téléchargées:
- Suppression de l'ensemble des demandes cochées 
- Affichage de la pop-in de confirmation de suppression 
***ou***
**Cas 2 :** Si au moins 1 demande n'a pas déjà été téléchargée:
- Les demandes sélectionnées ne sont pas supprimées
- Les cases de ces demandes sont décochées
- Affichage du message d'erreur 
Le message d'erreur ne doit pas indiquer précisément quelle(s) demande(s) n'a(n'ont) …
> [Lot 4] N°20 - Tableau de bord - Supprimer en masse

- client/app/demande/documents/documents.html
Attendu:
Côté demande usager (le côté tableau de bord agent est spécifié dans une autre carte)
Page Usager d’une demande en attente :
Les documents facultatifs seront toujours affichés
Le caractère conforme ou non conforme des documents complémentaires ne sera plus affiché :
Les documents facultatifs se voit attribuer un bandeau blanc (ni vert, ni rouge)
Aucun état n’est associé aux documents facultatifs ajoutés par l’usager à l’émission de sa demande
Lorsque l’usager clique sur « Ajouter un document », la mention "à renseigner" est présente dans l’entête blanche, sinon, aucune information n’est présente
> [Lot 4] N°06 - Demande - Bloquage de la modification des documents complémentaires d'une demande mise en attente

- server/components/pdf_structure/build.js
*EBE p.59*
**Dans les options de l'interface de configuration des exports :**
- **Situation actuelle : **
Dans un export ZIP d’une demande, le nom des intercalaires peut ne pas avoir de sens
- **Conséquences : **
Le nom de l’intercalaire peut ne pas refléter l’exhaustivité des documents concernés par l’intercalaire
- **Attendu : **
Donner à l’intercalaire le nom suivant : Separateur_[Nom de la catégorie] ou le nom du fichier source si la catégorie n’est pas nommée
> [Lot 4] N°26 - Tableau de bord - Donner à l’intercalaire le nom de sa catégorie ou le nom du fichier source si la catégorie n’est pas nommée

- client/app/dashboard/workflow/list/list.html
Fonctionnel OK, Design KO:
En responsive design, lorsque la largeur de la fenêtre est réduite, les liens Télécharger et Supprimer n'ont pas le même comportement. Leurs icônes respectives sont alignées à gauche pour télécharger, au centre pour Supprimer (Cf. PJ *Recette_gestionColonnesEnModeResponsive). L'alignement au centre est visuellement plus agréable, est-il possible d'homogénéiser le lien Télécharger de la même manière?
La continuité des interlignes grisées est rompue pour les demandes émsies et en attente sur les 2 dernières colonnes (Cf. PJ Recette_gestionColonnesInterlignes)
> [Lot 4_bugfix1] N°18 - Tableau de bord - Telecharger la demande dans le tableau de bord

- client/app/dashboard/workflow/list/list.controller.js
Recette KO:
Constat: Supprimer en masse ne fonctionne pas. Au clique sur le bouton Supprimer dans la pop-up de confirmation des suppressions, rien ne se passe.
> [Lot 4_bugfix1] N°20 - Tableau de bord - Supprimer en masse

- client/app/dashboard/workflow/detail/detail.js
- client/app/dashboard/workflow/detail/documents/documents.controller.js
Constat: dans le cas suivant, le bouton n'a aucune action associée: depuis les demandes émises, je clique sur une demande, je la valide (envoi accusé de réception), une fois l'envoi de l'accusé de réception confirmé dans via la pop-up, le bouton retour au flux des demandes n'entraîne pas la redirection vers les demandes émises.
> [Lot 4_bugfix1] N°29 - Tableau de bord - Retour au flux des demandes

- client/app/dashboard/users/agents/edit.controller.js
- client/app/dashboard/users/agents/edit.html
Création d'un agent
Au clic sur "Enregistrer" pour la création d'un nouvel agent, une page idnetique vide avec msg d'erreur apparaît un court instant avant la redirection adéquate.
Modification d'un agent
Présence inopinée du bloc informatif de modification de mot de passe (alors qu'on ne peut pas modifier le mot de passe de l'agent)
> [Lot 4_bugfix1] N°30 - Tableau de bord - Amélioration de la gestion des comptes agents

- server/api/profile/profile.controller.js
Lorsque je supprime la demande en cours de création, il n'y a pas de création de demande automatique ensuite (le demandeur dispose du bouton de création).
La demande n'est automatiquement créée qu'a la création d'un nouveau profil.
Dans le cas d'une connexion d'un demandeur avec 1 profil et 0 demandes en cours (car supprimée antérieurement), il arrive bien sur le tableau de bord des demandes comme prévu, avec 0 demandes et le bouton de création à dispo
> [Lot 4_bugfix1] N°13 - Profil et demandes - Supprimer une demande

- client/app/app.scss
- client/app/gestion/demande/gestion.demande.html
- client/app/gestion/gestion.scss
1 - Le bouton "Créer une nouvelle demande" n'est plus cliquable lorsqu'il est grisé (OK), mais il y a une erreur mineure : la souris passe de la flèche à la main indiquant à l'usager qu'il y a un élément cliquable (celà induit en erreur).
> [Lot 4_bugfix2] N°12 - Profil et demandes - Afficher la demande courante d'un profil

- client/app/app.scss
- client/app/gestion/demande/gestion.demande.html
Le titre "Demande de [prénom Nom] irrecevable" et le qualificatif "Demande irrecevable" à droite de la demande (supprimée ou irrecevable) ne correspondent pas à l'attendu.
-->OK pour le titre, KO pour la colonne tout à droite qui doit indiquer "Demande archivée"
Reste OK
> [Lot 4_bugfix2] N°14 - Profil et demandes - Afficher les demandes archivées et supprimées d'un profil

- client/app/dashboard/workflow/list/list.controller.js
A chaque déconnexion d'un utilisateur autre, puis reconnexion en tant qu'agent : 
- le panneau de navigation à gauche affiche soit :
- la moitié de la partie "Flux de demandes" (la moitié *Toutes les demandes*)
- uniquement la partie gestion des comptes agents
- Le rafraîchissement de la page permet de tout afficher comme attendu
Attendu : 
- Le rafraîchissement de la page par l'utilisateur ne devrait pas être nécessaire
> [Lot4_bug] N°bugB - Tableau de bord agent - affichage du panneau de navigation incomplet

- server/components/templates/identite.html
Dans le formulaire "Identité du bénéficiaire", la nationalité est manquante sur le récapitulatif affiché dans l'application ainsi que sur le PDF.
> [Ano lot3.2 - Mantis 7087] [Usager - PDF récapitulatif] Identité du bénéficiaire - Nationalité

- server/api/sections/sections.json
Les questions "Est-il placé en internat" (A) et "Dans quel établissement ?" (B) doivent être inversées dans le PDF récapitulatif afin d'apparaître dans cet ordre (A - B).
> [Ano lot3.2 - Mantis 7092] [Usager - PDF récapitulatif] Vie scolaire ou étudiante - Ordre d'affichage

- server/api/sections/sections.json
Lorsque la date est saisie, le PDF indique : 
"* Oui
° 11/11/1111"
Il faudrait ajouter "Depuis le" avant la date, tel que : 
"* Oui
° Depuis le 11/11/1111"
> [Ano lot3.2 - Mantis 7094] [Usager - PDF récapitulatif] Vie au travail - Question "Avez-vous actuellement un emploi ?"

- server/api/sections/sections.json
Lorsque la date est saisie, le PDF indique :
"* Oui
° 11/11/1111"
Il faudrait ajouter "Depuis le" avant la date, tel que :
"* Oui
° Depuis le 11/11/1111"
> [Ano lot3.2 - Mantis 7095] [Usager - PDF récapitulatif] Vie au travail - Question "Êtes-vous actuellement en arrêt de travail ?"

- client/components/detail/precisez_date_et_detail.html
Correction du ticket initial OK
[Constaté le 19/03/2018]
L'icone [fa-warning] devant le message d'erreur "/!\ Ce champ est obligatoire" associées aux réponses :
"Vous commencez bientôt une nouvelle formation"
et
"Vous venez de trouver un emploi"
a bien été ajouté, cependant, il manque un espace entre l'icone et le message.
> [Ano lot3.2 - Mantis 7049] [Usager - Formulaire] Situations particuliaires - Orthographe du message d'erreur

- server/api/prestation/prestations.json
La prestation "Parcours de scolarisation et/ou de formation avec ou sans accompagnement par un établissement ou service médico-social." est la seule à avoir un point en fin de phrase. Serait-il possible de le retirer ?
> [Ano lot3.2 - Mantis 7105] [Usager - PDF récapitulatif et Formulaire] Prestations - Parcours de scolarisation

- server/api/sections/sections.json
Dans le formulaire "Vie scolaire ou étudiante" adulte (>20 ans) et dans les PDF récapitulatifs (Adulte et enfant), modifier la question à la deuxième personne du pluriel :
"Êtes-vous placé en internat ?"
> [Ano lot3.2 - Mantis 7091] [Usager - PDF récapitulatif et formulaire] Vie scolaire ou étudiante - Question "Est-il placé en internat"

- client/app/demande/identites/beneficiaire.js
Constaté le 04/05/2018
Lors du premier passage sur le formulaire Vie quotidienne, à la suite du chaînage avec un profil usager ayant moins de 20 ans, les quatres réponses s'affichent à la question : 
"[Non Prénom] recoit les aides, ressources et/ou prestations suivantes :" 
Il ne devrait y avoir que les réponses : 
- "Allocation Adulte Handicapé (AAH)" 
- "Allocation chômage versée par Pôle Emploi"
> [Ano lot3.2 - Mantis 7085] [Usager - Vie quotidienne < 20 ans] Question "[Non Prénom] recoit les aides, ressources et/ou prestations suivantes : "

- client/app/demande/projet_de_vie/vie_au_travail/situation_professionnelle.js
- client/components/question/employeur.html
- client/components/question/question.controller.js
Constaté le 09/05/2018 : 
Lorsque l'usager saisit des réponses à la question "Qui est votre employeur", les réponses ne sont pas supprimées s'il clique sur le bouton "Précédent". 
Par conséquent, s'il change de chemin suite à une erreur, l'information est tout de même enregistrée dans la demande et affichée dans le PDF récapitulatif. 
Pourriez-vous mettre en place le même fonctionnement que pour les autres questions ? A savoir : 
Suppression des informations saisies lors du clic sur "Précédent".
> [Ano lot3.2 - Mantis 7086] [Formulaire - Vie au travail] Erreur de suppression lors du clic sur "Précédent"

- client/app/gestion/demande/gestion.demande.controller.js
- client/app/gestion/demande/gestion.demande.html
- client/app/gestion/gestion.scss
Pour harmonisation avec la page de gestion des profils :
1. la colonne de droite qui sert à l'affichage de l'icône demande, occupe 15% de l'écran, merci de retirer l'élément style de la div et laisser une largeur définie par bootstrap : col-md-2
2. le bouton de retour aux profils devrait également occuper toute la largeur de la colonne de droite
3. de même retirer la définition de largeur sur le corps de la page et utiliser les largeurs définies par défaut : col-md-10
Plusieurs anomalies de libellés détectées :
1. merci de passer au féminin le participe passé du verbe créer pour les demandes archivées : "Créée"
2. les états affichés des demandes doivent être affichés comme suit, avec une majuscule :
- « Validée »
- « Irrecevable »
> lot4 - Mantis 7146 [Usager][Gestion des demandes] : Anomalies graphiques

- client/app/demande/documents/documents.controller.js
- client/components/service/upload.service.js
- server/api/document/document.controller.js
Connecté en tant qu'usager, il est très désagréable d'utiliser la page d'upload des documents lorsque l'on remplit initialement le questionnaire ou que la demande est en attente : 
- l'upload d'un document engendre systématiquement un rechargement de la page, l'utilisateur perd le focus (position à laquelle il était dans la page),
- si le premier upload n'est pas terminé et que l'utilisateur lance un second upload, ce-dernier est interrompu
Ces deux comportements ne sont pas satisfaisants, merci de les corriger.
> [RC lot4 - Mantis 7139] [Usager][Saisie demande - Document] : Rechargement intempestif de la page

- client/app/dashboard/workflow/list/list.controller.js
- client/app/dashboard/workflow/list/list.html
Connecté en tant qu'agent, sur tous les tableaux de bord de gestion des demandes (mes demandes, toutes les demandes) et tous états, le bouton "Rafraîchir" ne fonctionne pas.
> [RC lot4 - Mantis 7158 - P1] [Agent][Tableau des demandes] : Bouton rafraîchir ne fonctionne pas

- server/components/recapitulatif.js
Lorsque le demandeur indique être un stagiaire rémunéré, le PDF récapitulatif indique que le stage n'est pas rémunéré. 
Dans le cas où l'usager coche "Oui" à la sous-question "Est-ce un stage rémunéré ?", merci d'afficher dans le PDF récapitulatif : 
"* Stagiaire professionnel
° stage rémunéré"
> [Ano lot3.2 - Mantis 7101] [Usager - PDF récapitulatif] Vie au travail - Question "Quel est votre type d'emploi ?"

- client/app/dashboard/workflow/list/list.html
Connecté en tant qu'agent, il est actuellement possible de faire passer une demande "validée" à l'état "irrecevable". Cette transition n'a pas été autorisée dans les workflow, merci de retirer l'option "marquer comme irrecevable" de la liste des actions possibles sous le bouton d'actions groupées.
> [Ano lot4 - Mantis 7155] [Agent][Tableau des demandes validées] : Passage 'validée' à 'irrecevable' autorisé

- client/app/demande/unconfirmed/unconfirmed.html
Connecté en tant qu'usager, sur la page de confirmation du compte mail accessible depuis la page d'une demande en cours (url au format : [domaine]/mdph/19/demande/Sy7nHXVeX/unconfirmed), le fil d'Ariane affiché n'est pas celui attendu :
- il commence par "Profil /" alors qu'il doit commencer par "Demande /"
- le lien sous "Profil" n'est pas fonctionnel
- le bouton d'envoi du mail de confirmation n'est pas fonctionnel (un paramètre manque à l'appel de la page...)
> [RC lot4 - Mantis 7134 - P1] [Usager][Saisie demande - Confirmer votre compte mail] : Fil d'Ariane KO

- server/api/request/request.controller.js
- server/api/request/request.model.js
Il a été explicitement demandé que les profils ne contiennent plus que quelques données :
1. les données d'identités du bénéficiaire ; 
2. les données de l'autorité parentale.
Aujourd'hui, le profil contient des données de deux formulaires de trop :
- Identité du représentant légal
- Identité de la personne vous aidant dans cette démarche
> [RC lot4 - Mantis 7143 - P0] ][Usager][Profil] : Erreur lors du renouvellement

- server/components/pdf_utils/archive.js
La présence du caractère "/" dans les éléments suivants est mal géré lors d'export ZIP d'une demande :
- le nom de la catégorie ;
- le nom d'un type de documents (classé dans une catégorie).
En effet, le caractère / est interprété comme un chemin dans l'archive et les documents téléchargés sont inexploitables.
Lors de la génération de l'archive ZIP, il faudrait peut être remplacer le "/" par "_" afin que l'anomalie ne soit plus observée.
> [RC lot4 - Mantis 7136 - P1] [Technique][Agent] : Anomalie dans les exports ZIP

- client/components/timeline/action-types.constant.js
Connecté en tant qu'agent, 
- la vie de la demande consultable dans l'onglet "vie de la demande" de la fiche détail d'une demande n'est pas lisible.
- De nombreuses actions "de type inconnu" sont enregistrées, que ce soit des actions des agents ou des actions des usagers.
> [RC lot4 - Mantis 7152 - P2] [Agent][Détail d'une demande] : Vie de la demande illisible

- client/app/dashboard/workflow/workflow.controller.js
- server/api/request/request.controller.js
En tant qu'agent, il est possible de télécharger une demande déjà supprimée.
Scénarios envisagés :
actualisation d'un lien téléchargement alors que par ailleurs la demande a déjà été supprimée
usage concurrentiel du tableau de bord par 2 agents, l'un supprime, l'autre télécharge.
Les conséquences de cette simple requête à l'API sont alors fatales au service qui est automatiquement mis hors service.
Il semble préférable, pour la disponibilité du service, de gérer l'exception "requête de téléchargement d'une demande supprimée".
> [RC lot4 - mantis 7132 - P0] [Technique][Agent] : Téléchargement d'une demande supprimée

- client/app/gestion/gestion.scss
- client/app/gestion/profil/gestion.profil.html
Sur la page de gestion des profils :
- le passage au responsive rend les boutons d'accès aux profils carrés, merci de reprendre un design avec des bords arrondis
Sur les pages de gestion des profils et page de gestion des demandes :
- sur de petits écrans, le fil d'Ariane "Profils > Demandes " n'est plus affiché convenablement : Demandes passe sous Profils en escalier
- les pages présentent des marges latérales trop importantes, nous pensons qu'il serait possible de gagner de la place (notamment pour les boutons supprimer)
- une passe globale en responsive sur ces deux écrans est attendue.
> [RC lot4 - mantis 7153 - P2] [Usager][Gestion des profils et demandes] : Responsive W. Design

- client/app/gestion/demande/gestion.demande.html
- client/app/gestion/gestion.scss
- client/app/gestion/profil/gestion.profil.html
le fil d'Ariane et le bouton "Retour aux profil" doivent être de la même largeur que les boutons du tableau de bord : KO
Le fil d'Ariane est s'ajuste bien à la largeur du bouton "Retour profil"
Effet de bord : quand on met la fenêtre au plus petit (ou sur téléphone) on ne vois plus la partie droite de l'écran. Il faut scroller verticalement pour accéder au bouton supprimer.
La partie de droite a un fond d'écran blanc et non pas bleu.
> [lot4 - Mantis 7153 - bugfix01] Responsive Design de la gestion des profils
