README.md
client/app/demande/steps/steps.scss
client/components/detail/precisez_date.html
client/components/question/textinput.html
server/api/sections/sections.json

Minor fixes

---

client/app/dashboard/documents/categories/categories.controller.js
client/app/dashboard/documents/categories/categories.html
client/app/dashboard/documents/categories/categories.scss
client/app/dashboard/documents/documents.js
client/components/resources/mdph.resource.js
server/api/document/document-category.controller.js
server/api/document/document-category.model.js
server/api/mdph/index.js
server/api/mdph/mdph.controller.js
server/components/pdf_structure/build.js

Il faut pouvoir ajouter des types de documents dans la catégorie "Justificatifs de demande"

Make required category editable

---

client/app/dashboard/workflow/list/request-table-body.html
client/components/string/capitalize.filter.js

change the filter for the name in the list

---

.jscsrc
client/app/stats/stats.controller.js
client/components/auth/interceptor.service.js
client/components/util/util.service.js

Besoin de le reactiver pour que la BAN ne rale pas, le probleme semble venir de $window.location sur IE11 qui ne remplis pas le port.

Same origin

---

client/app/account/login/login.controller.js
client/app/account/login/login.controller.spec.js
client/app/account/signup/signup.controller.spec.js

juste pour info, quelques subtilités (ui router avec $scope.apply et catch à la fin du login)

add login test

---

client/app/account/signup/signup.controller.js
client/app/account/signup/signup.html
client/app/profil/demande/demande.html

Signup multi profiles

---

client/app/account/signup/signup.controller.js
client/app/account/signup/signup.html

Revert "Signup multi profiles"

---

client/app/profil/aidant/aidant.js
client/app/profil/aidant/situation.js
client/app/profil/aidant/vos_attentes.js
client/app/profil/projet_de_vie/vie_au_travail/parcours_professionnel.js
client/app/profil/projet_de_vie/vie_au_travail/projet_professionnel.js
client/app/profil/projet_de_vie/vie_au_travail/situation_professionnelle.js
client/app/profil/projet_de_vie/vie_au_travail/situation_professionnelle/emploi.js
client/app/profil/projet_de_vie/vie_au_travail/situation_professionnelle/sans_emploi.js
client/app/profil/projet_de_vie/vie_au_travail/vie_au_travail.js
client/app/profil/projet_de_vie/vie_quotidienne/situation.js
client/app/profil/projet_de_vie/vie_quotidienne/vie_quotidienne.js
client/app/profil/projet_de_vie/vie_quotidienne/vosattentes.js
client/app/profil/projet_de_vie/vie_quotidienne/vosbesoins.js
client/app/profil/projet_de_vie/vie_scolaire/situation.js
client/app/profil/projet_de_vie/vie_scolaire/vie_scolaire.js
client/app/profil/projet_de_vie/vie_scolaire/vosattentes.js
client/app/profil/projet_de_vie/vie_scolaire/vosbesoins.js
client/app/profil/section.controller.js
client/app/profil/situations_particulieres/situations_particulieres.js
client/components/question/question.controller.js
client/components/question/textinput.html
client/index.html
e2e/account/request/request.spec.js
e2e/account/request/signuptunnel.spec.js
karma.conf.js
package.json
server/api/user/user.integration.spec.js

Avant:
- Je souhaite faire une nouvelle demande.
- Dans la 1ere demande j'ai répondu que j'ai un emploi
- Dans la question suivante j'ai indiqué que j'ai un CDD
- Je reviens, j'indique que je suis sans-emploi, le formulaire ne demande plus si je suis en CDD ou non, donc on introduit une information erronée
Après:
- Seules les nouvelles réponses sont sauvegardées
- On ne garde plus d'URL spécifiques pour les réponses pour ne pas avoir de nouvelles réponses tronquées a partir de l'URL

Meilleur traitement des renouvellements de demandes

---

client/app/profil/aidant/situation.js
client/app/profil/projet_de_vie/vie_au_travail/situation_professionnelle.js
client/app/profil/projet_de_vie/vie_quotidienne/situation.js
client/app/profil/projet_de_vie/vie_scolaire/situation.js
client/app/profil/situations_particulieres/situations_particulieres.js
client/components/nav-steps/nav-steps.directive.js
client/components/nav-steps/nav-steps.html

Le bouton "Question précédente" ne fonctionne plus car il utilisais les url relatives sur les questions. Ce bouton ne servira donc plus qu'a revenir a l'ecran de profil.

Suppression de la fonctionnalité "Question précédente"

---

client/app/dashboard/workflow/list/list.controller.js
client/app/dashboard/workflow/list/list.html
client/components/resources/mdph.resource.js
server/api/mdph/index.js
server/api/mdph/mdph.controller.js

J'en ai profité pour ré-écrire la fonction qui retourne la liste des secteurs car on a pas besoin de la version contentant toutes les demandes à cet endroit.

En tant qu'agent MDPH, je ne peux pas faire d'actions supplémentaires sur les demandes archivées

---

Dockerfile
Gruntfile.js
README.md
circle.yml
grunt-tasks/copy.js
grunt-tasks/injector.js
grunt-tasks/ngtemplates.js
grunt-tasks/sass.js
package.json
yarn.lock

Avant:
Après:
On économise plus de 4s de build sur ma machine.

Utiliser node sass plutôt que ruby

---

package.json

See @nickcmaynard comment in https://github.com/angular/protractor/issues/4141
Ping @fonzarely

Use selenium 3.2.0 as latest is broken

---

README.md
pm2.json

Pour pouvoir déployer facilement sur la machine vagrant

Ajouter la config vagrant dans le fichier example PM2

---

client/app/departement/departement.html
client/app/layout/layout.scss
client/app/main/main.scss
client/app/profil/profil.html
client/app/profil/profile.scss
client/components/mes_profils/mes_profils.scss

Améliorer le rendu mobile du formulaire de demande

---

client/app/profil/demande/demande.controller.js
client/app/profil/demande/demande.html
client/components/generic-modal/generic-modal.html
server/api/send-mail/send-mail.controller.js

https://trello.com/b/kAkHOIj0/mdph-en-ligne

ETQ utilisateur, je comprend que j'ai recu un email necessaire pour la validation / l'envoi de la demande

---

client/components/mdph-map/mdph-map.controller.js

https://trello.com/c/RnxL1xLk/410-etq-utilisateur-si-la-mdph-n-a-pas-de-tel-mail-etc-je-ne-vois-pas-des-zones-texte-vides

ETQ Utilisateur, si la MDPH n'a pas de tel / mail / etc je ne vois pas des zones texte vides

---

client/components/footer/footer.component.js
client/components/footer/footer.html
client/components/footer/footer.scss
client/components/mdph-map/mdph-map.controller.js
server/api/mdph/mdph.model.js

https://trello.com/c/qUOmuGdn/409-etq-mdph-je-souhaite-que-mon-siege-soit-facilement-distinguable-des-autres-adresses
Il faut maintenant ajouter le boolean "headquarter" sur toutes les locations "siège" des MDPH.
@laurentcommeau j'ai uniformisé le layout ici.

ETQ MDPH je souhaite que mon siège soit facilement distinguable des autres adresses

---

client/components/footer/footer.component.js
client/components/footer/footer.scss

Remove console error

---

client/app/partenaire/pj/pj.html
server/api/request/request.controller.js

ETQ que médecin ou partenaire, je sais à quel bénéficiaire est associé une demande.

---

client/app/main/main.html
client/app/main/main.scss
client/components/mdph-input/mdph-input.component.js
client/components/mdph-input/mdph-input.controller.js
client/components/mdph-input/mdph-input.html
client/index.html

On entre le numéro de son département pour trouver la page correspondante.

ETQ Utilisateur je trouve ma MDPH meme si elle n'est pas encore ouverte - Input

---

client/app/profil/demande/choix_mdph/choix_mdph.html
client/app/profil/demande/demande.html
client/app/profil/demande/demande.scss
server/api/partenaire/partenaire.controller.js

- Mise en avant de l'identifiant de demande pour faciliter sa transmission aux partenaires/médecins
- Ajout de titres "Documents à joindre à votre demande", "Expression des demandes de droits et prestations" et "Vous avez déjà un dossier à la MDPH ?" conformément au PDF

Uniformiser l'écran nouvelle demande avec le modele PDF de demande

---

client/app/departement/departement.html
client/app/main/main.html

https://trello.com/c/Ga3iYXYL/447-etq-usager-je-comprend-les-%C3%A9tapes-de-transmission-de-ma-demande-sur-la-page-daccueil

ETQ usager, je comprend les étapes de transmission de ma demande sur la page d'accueil

---

client/app/dashboard/list.scss
client/app/dashboard/workflow/list/list.controller.js
client/app/dashboard/workflow/list/list.html
client/app/dashboard/workflow/list/list.js
yarn.lock

https://trello.com/c/tHX0JR6d/445-etq-agent-mon-tableau-de-bord-ne-sactualise-pas

EQT agent, je souhaite pouvoir actualiser mon tableau de bord

---

client/app/app.scss
client/app/profil/demande/demande.controller.js
client/app/profil/demande/demande.controller.spec.js
client/app/profil/demande/demande.js
client/app/profil/demande/prestations/prestations.html
client/app/profil/demande/prestations/prestations.scss
client/app/profil/demande/prestations/prestations.well.scss
client/components/prestations/prestation.component.js
client/components/prestations/prestation.html
client/components/prestations/prestation.scss
client/index.html
server/api/prestation/prestations.json

ETQ usager, je retrouve sur le service en ligne la même liste de prestations que le formulaire papier, organisées de la même façon

---

client/app/profil/profile.scss
client/components/question/questions.scss

https://trello.com/c/sGqgxzyY/480-etq-utilisateur-je-vois-plus-facilement-quelle-reponse-est-selectionnee

ETQ utilisateur, je vois plus facilement quelle reponse est selectionnee

---

client/app/profil/profil.html

https://trello.com/c/ldJvFZQR/470-etq-utilisateur-je-ne-peux-pas-envoyer-de-nouvelle-demande-si-ma-demande-actuelle-nas-pas-encore-%C3%A9t%C3%A9-trait%C3%A9e

ETQ utilisateur, je ne peux pas envoyer de nouvelle demande si ma demande actuelle n'as pas encore été traitée

---

client/app/dashboard/documents/documents.controller.js
client/app/dashboard/documents/documents.html
client/app/dashboard/documents/documents.scss
client/app/dashboard/workflow/list/list.controller.js
client/components/resources/mdph.resource.js
package.json
server/api/document-category/document-category.controller.js
server/api/document-category/index.js
server/api/mdph/mdph.controller.js
server/api/mdph/mdph.model.js
server/api/request/request.controller.js
server/components/pdf-maker.js
server/components/pdf_structure/build.js
server/components/pdf_structure/build.spec.js
server/components/pdf_structure/writeGridfsToFile.js
server/components/pdf_utils/archive.js
server/components/pdf_utils/join.js
yarn.lock

https://trello.com/c/c0BZnfQc/448-etq-agent-je-peux-t%C3%A9l%C3%A9charger-une-demande-au-format-zip-dans-laquelle-chaque-fichier-correspond-%C3%A0-un-intercalaire-de-la-ged

ETQ agent, je peux télécharger une demande au format zip dans laquelle chaque fichier correspond à un intercalaire de la GED

---

client/app/cgu/cgu.html

Compléter les CGU

---

client/app/profil/profil.controller.js
server/api/sections/sections.json

https://trello.com/c/gzCEXngG/482-etq-usager-le-d%C3%A9tail-associ%C3%A9-aux-r%C3%A9ponses-dans-la-partie-vie-scolaire-ou-%C3%A9tudiante-est-correct

ETQ usager, le détail associé aux réponses dans la partie "Vie scolaire ou étudiante" est correct

---

client/app/apropos/apropos.js
client/app/cgu/cgu.js
client/components/auth/auth.service.js
client/components/footer/footer.html

https://trello.com/c/6D38hhFM/514-etq-cnsa-je-souhaite-retirer-la-page-de-cgu-tant-quelle-nest-pas-validee-par-un-juriste-agr%C3%A9%C3%A9-cnsa

ETQ CNSA je souhaite retirer la page de CGU tant quelle n'est pas validee par un juriste agréé CNSA.

---

client/components/upload/upload.service.js
server/api/request/index.js
server/api/request/request.controller.js
server/api/request/request.model.js
server/api/send-mail/send-mail-actions.js
server/api/send-mail/send-mail-actions.spec.js
server/api/send-mail/send-mail.controller.js
server/api/synthese/synthese.controller.js
server/components/mailsender/mail-sender.js
server/components/mailsender/mail-sender.spec.js
server/components/pdf-maker.js
test/utils/seed.js

https://trello.com/c/18n0Q8Kz/515-etq-usager-je-r%C3%A9pond-directement-%C3%A0-la-mdph-ou-jai-fait-ma-demande

ETQ usager, je répond directement à la MDPH ou j'ai fait ma demande

---

client/components/display-file/display-file-modal.html
client/components/display-file/display-file.directive.js
client/components/display-file/display-file.html
client/components/display-file/display-file.scss

ETQ agent, je souhaite avoir un affichage des PJs dans mon navigateur

---

client/components/display-file/display-file.directive.js
client/components/display-file/display-file.html
server/api/document/index.js
server/api/request/index.js
server/auth/auth.service.js

https://trello.com/c/iBZgYgVQ/462-en-tant-quagent-mdph-je-ne-peux-pas-supprimer-les-pi%C3%A8ces-jointes-pour-ne-pas-compromettre-lint%C3%A9grit%C3%A9-dun-dossier

En tant qu'agent MDPH, je ne peux pas supprimer les pièces jointes, pour ne pas compromettre l'intégrité d'un dossier

---

client/components/detail/precisez_pourcent.html
client/components/qtitle/qtitle.html
client/components/question/autres_renseignements.html
client/components/question/checkbox.html
client/components/question/date.html
client/components/question/droits.html
client/components/question/radio.html
client/components/question/structure.html
client/components/question/textarea.html
client/components/question/textinput.html
server/api/sections/sections.json

https://trello.com/c/1Lx96BNV/483-etq-usager-je-ne-vois-pas-de-fautes-dans-les-libell%C3%A9s-des-titres-des-pages-de-formulaire
https://trello.com/c/tmeYNsYR/484-etq-usager-les-questions-ou-r%C3%A9ponses-des-formulaires-sont-affich%C3%A9es-de-mani%C3%A8re-uniforme

ETQ usager, je ne vois pas de fautes dans les libellés des titres des pages de formulaire

---

server/api/sections/sections.json

Remplacement des [...] par [, etc.], forme la plus correcte. - cf Carte : https://trello.com/c/ecazQyjx

Uniformisation du format des fins de listes non finies

---

client/app/admin/activation/admin.activation.controller.js

Remplacement de "Compte inconu" en "Compte inconnu"

Correction orthographique

---

client/app/evaluation/detail/evaluation.detail.controller.js
client/app/evaluation/detail/evaluation.detail.html
client/components/trajectoire/trajectoire.component.js
client/components/trajectoire/trajectoire.controller.js
client/components/trajectoire/trajectoire.html
client/components/trajectoire/trajectoire.scss
server/api/synthese/synthese.model.js

Description du comportement attendu :
• l’usager voit apparaitre un bouton « Déficience principale » à gauche du bouton « Commenter », au survol de la souris et uniquement sur les questions relatives aux déficiences ;
• lors du clic, le fond de l’élément devient orange et le bouton déficience principale reste affiché, mais l’usager peut à tout moment changer la déficience principale en cliquant sur le bouton « Déficience principale » d’un autre élément, ou annuler la mise en avant de la déficience en cliquant de nouveau sur le bouton « Déficience principale ».

[Lot3] n°38 ETQ utilisateur de l’outil de soutien, je peux mettre en avant la déficience principale d’un patient

---

client/app/evaluation/detail/evaluation.detail.controller.js
client/app/evaluation/detail/evaluation.detail.html
client/app/evaluation/detail/evaluation.detail.js
client/components/evaluation-synthese-add-empty/evaluation-synthese-add-empty.controller.js

[LOT3] n°32 => la création de la synthese ne se fait que lors de l'enregistrement de la premiere information saisie

ETQ utilisateur de l’outil de soutien, je ne peux pas créer de fiches de synthèse vides

---

client/app/evaluation/detail/evaluation.detail.controller.js
client/app/evaluation/detail/evaluation.detail.html

faire l'autocomplétion de la date et ne l'enregistrer qu'une fois modifiée et la saisie est complète.

ETQ utilisateur de l'outil de soutien, la mise en forme de la date de naissance est automatique lors de la saisie

---

client/app/app.scss
client/app/dashboard/workflow/detail/detail.html
client/app/dashboard/workflow/detail/detail.js
client/app/dashboard/workflow/detail/pre_evaluation/pre_evaluation.html
client/app/dashboard/workflow/detail/validation_depot/validation_depot.controller.js
client/app/dashboard/workflow/detail/validation_depot/validation_depot.html
client/app/dashboard/workflow/detail/validation_depot/validation_depot.scss
client/app/dashboard/workflow/list/list.html
client/app/profil/prestations/prestations.controller.js
client/app/profil/prestations/prestations.html
client/app/profil/prestations/prestations.js
client/components/menu-dashboard/menu-dashboard.html
client/components/prestations/prestation.component.js
client/components/prestations/prestation.html
client/index.html
server/api/document/document.integration.spec.js
server/api/prestation/prestation.controller.js
server/api/prestation/prestations.json
server/api/request/request.integration.spec.js
server/api/request/request.model.js
server/components/pdf-maker.js
server/components/templates/prestations.html

**Constat :**
A) Au clic sur une case à cocher, il s'affiche systématiquement une autre case à cocher intitulé "Je perçois déjà cette prestation"
B) La case à cocher "Accompagnement par un service ou établissement médico-social" s'affiche.
C) La case à cocher "Parcours de scolarisation et/ou de formation avec ou sans accompagnement par un établissement ou service médico-social." s'affiche.
**Attendu :**
A) Ne jamais plus afficher la case "Je perçois déjà cette prestation"
B) Remplacer le texte par "Maintien en établissement ou service médico-social (ESMS) au titre de l'amendement Creton". (Cette case doit toujours être visible uniquement par les plus de 20 ans.)
C) Lorsque cette case est cochée, afficher une boite de texte intitulé « Précisez éventuellement votre demande » juste en …

[Lot3] n°27 ETQ Bénéficiaire : Modifications du questionnaire "Expression des demandes de droits et prestations"

---

client/app/profil/aidant/aidant.js
client/app/profil/identites/autorite.js
client/app/profil/identites/beneficiaire.js
client/app/profil/identites/representant.js
client/app/profil/projet_de_vie/vie_quotidienne/vie_quotidienne.js
client/app/profil/situations_particulieres/situations_particulieres.js

NB: ça implémente aussi les tickets 5 et 6.
Constat:
Aujourd'hui, le chainage comporte :
o « Identité du bénéficiaire »
o « Identité de l’autorité parentale » (si les conditions sont remplies)
o « Vie quotidienne »
L’enchainement des formulaires reprend lorsque l’usager revient sur la page d’accueil du profil et retourne dans ces questionnaires
Attendu :
L'ordre attendu dans le chainage est :
o « Identité du bénéficiaire »
o « Identité de l’autorité parentale » (si les conditions sont remplies)
o « Identité de la personne vous aidant dans cette démarche » (si les conditions sont remplies)
o « Identité du représentant légal » (si les conditions sont remplies)
o « Situations particulières »
o « Vie quotidienne »
o « Documents »
L’enchainement des formulaires reprend lorsque l’usager revient …

[Lot3.2] n°07 ETQ Bénéficiaire : Identification et ordre d'affichage des questionnaires dans le chainage.

---

client/app/profil/identites/beneficiaire.html
server/components/register-handlebars.js
server/components/templates/identite.html

Constat:
Absence de 2 questions.
Attendu:
Ajouter les 2 questions suivantes (Cf image jointe) :
« Êtes-vous aidé.e dans vos démarches auprès de la MDPH ? » avec les réponses "Oui" et "Non".
« Bénéficiez-vous d’une mesure de protection ? » avec les réponses "Oui" et "Non".
Ces champs sont obligatoires
Ces chamsp et les données saisies doivent apparaitre dans le PDF CERFA.
Note : Les réponses à ces questions impactent l'affichage des questionnaires dans le chainage (cf cartes n°03, n°04, et n°07).

[Lot3.2] n°09 ETQ Bénéficiaire : Ajout de deux questions, dont les réponses impactent le chainage.

---

client/app/profil/aidant/aidant.js
client/app/profil/identites/autorite.js
client/app/profil/identites/beneficiaire.js
client/app/profil/identites/representant.js
client/app/profil/identites/representants.html
client/components/representant-form/representant.component.js
client/components/representant-form/representant.controller.js
client/components/representant-form/representant.html
server/components/register-handlebars.js
server/components/templates/identites.html
server/components/templates/representant.html
server/components/templates/representants.html

Constat :
Ce questionnaire n'existe pas aujourd'hui et sera à créer dans la carte n°26.
Attendu:
Si l'utilisateur a saisi "Oui" à la question « Bénéficiez-vous d’une mesure de protection ? » dans le questionnaire "Identité bénéficiaire", alors le questionnaire "Identité du représentant légal" s'affiche dans le chainage.
Si l'utilisateur a saisi "Non", alors le questionnaire ne s'affiche pas dans le chainage.
Si le questionnaire s'affiche dans le chainage, il s'affiche :
1) Derrière le questionnaire "Identité de la personne vous aidant dans cette démarche" s'il s'affiche.
2) Derrière le questionnaire "Identité de l'autorité parentale" s'il s'affiche et si "Identité de la personne vous aidant dans cette démarche" ne s'affiche pas..
3) Derrière "Identité bénéficiaire" si les questionnaires …

[Lot3.2] n°04 ETQ Bénéficiaire : Affichage du chainage du questionnaire "Identité du représentant légal" et l'ajouter dans le PDF

---

client/app/profil/projet_de_vie/vie_quotidienne/situation.js
server/api/sections/sections.json

Constat:
Il manque 2 questions
Attendu :
1) Ajout de la question "Vous avez déjà eu" :
Où : entre la question "Où vivez-vous?" et "vous recevez"
Réponses :
- case à cocher "Un accident causé par un tiers"
- case à cocher "Un accident du travail"
- case à cocher "Un autre accident" + le formulaire "Précisez" et un champ de saisie
2) Si l'une des réponses est cochée, le système redirige vers la question "Suite à cet accident y a-t-il une demande d'indemnisation en cours ou ayant abouti ?".
Si aucune des réponses n'est cochée, le système redirige directement vers la question "vous recevez".
3) Ajout de la question "Suite à cet accident y a-t-il une demande d'indemnisation en cours ou ayant abouti ?" :
Où : Juste après "Vous avez déjà eu"
Réponses :
- Bouton radio "Oui" + le formulaire …

[Lot3.2] n°11 ETQ Bénéficiaire : ajouter 2 questions dans le questionnaire "Vie quotidienne"

---

client/app/profil/projet_de_vie/vie_quotidienne/situation.js
client/components/detail/precisez_2_details.html
client/components/detail/precisez_pourcent.html
server/api/sections/sections.json
server/components/recapitulatif.js

Constat : 
Il n'existe pas de 2 questions.
Attendu :
1.1) Ajout de la question « Du fait du handicap de [NOM ENFANT] : », uniquement visible pour les moins de 20 ans :
Où? Avant la question « Frais liés au handicap et restant à charge ».
Réponses :
- case à cocher "Vous exercez une activité professionnelle à temps partiel" + le formulaire avec le champ de saisie libre « Précisez la quotité en pourcentage », avec le placeholder "__%"
- case à cocher "Vous avez dû renoncer à votre emploi"
.1.2) Si aucune réponse n'est sélectionnée, l'utilisateur peut cliquer sur "Question suivante".
Si la réponse "Vous exercez une activité professionnelle à temps partiel" est cochée et son champ de saisie vide, "Question suivante" est grisé et désactivé.
Enfin si ce champ de saisi est rempli, "Question …

[Lot3.2] n°16 ETQ Bénéficiaire : ajout de 2 questions pour les moins de 20 ans dans le questionnaire "Vie quotidienne"

---

server/components/recapitulatif.js
server/components/templates/question.html

CERFA : conserver le format de la réponse de l'application --> en 2

[Lot3.2_bugfix01] n°16 ETQ Bénéficiaire : ajout de 2 questions pour les moins de 20 ans dans le questionnaire "Vie quotidienne"

---

client/app/profil/profil.controller.js
client/app/profil/profil.html
client/components/profile/profile.service.js

le bloc "Identité de la personne vous aidant dans cette démarche"  doit être toujours affiché

[Lot3.2_bugfix2] n°03 ETQ Bénéficiaire : Affichage du chainage du questionnaire "Identité de la personne vous aidant dans cette démarche"

---

server/components/recapitulatif.js

Les sous-réponses sont sur 2 sous-lignes différentes : OK
Présence d'un mot supplémentaire "undefined" au début de la deuxième ligne : KO
=>
supprimer undefined dans la deuxieme réponse

[Lot3.2_bugfix02] n°16 ETQ Bénéficiaire : ajout de 2 questions pour les moins de 20 ans dans le questionnaire "Vie quotidienne"

---

client/components/prestations/prestation.html

Le bouton "En savoir plus" ne doit pas retourner à la ligne après le choix

[Lot3.2_bugfix01] n°27 ETQ Bénéficiaire : Modifications du questionnaire "Expression des demandes de droits et prestations"

---

client/app/app.js

Lot3 2 recettepasse2 rafraichissement bloc confirmer compte mail IE

---

server/api/sections/sections.json

différencier la réponse entre les adultes et les mineurs

[Lot 3.2_RecettePasse2] Mantis 7048 ETQ bénéficiaire de -20 ans, les réponses sont à la 3ème personne du singulier dans le formulaire Vie quotidienne

---

client/app/profil/identites/autre.html
client/app/profil/identites/beneficiaire.html
client/app/profil/profil.controller.js
client/app/profil/projet_de_vie/vie_quotidienne/situation.js
client/components/detail/domicile.html
client/components/question/pourcentageinput.html
client/components/representant-form/representant.html
package.json
server/api/sections/sections.json
server/components/recapitulatif.js
server/components/templates/identite.html
server/components/templates/representant.html

Dans Vie quotidienne, à la question : Où vivez-vous ? La sous-réponse de "Vous êtes hébergé·e au domicile" est 'enfants'
Les pays des adresses ne sont pas affichés
Connaissez-vous votre taux d'IPP (Incapacité Permanente Partielle) ?
7/20
La réponse ne contient pas '%'
Dans Vie scolaire et étudiante, à la question "Est-il pacé en internat?" la réponse Oui est affichée puis la sous-réponse 'true'
à la question "Connaissez-vous votre taux d'IPP (Incapacité Permanente Partielle)?" le taux n'est pas borné à 100 comme d'autres taux du formulaire. Ainsi dans le PDF je retrouve un taux à 87768%
Proposition : ajouter "%" dans le PDF

[Lot3.2_RecettePasse2] Bug d'affichage des réponses dans le CERFA

---

client/app/profil/projet_de_vie/vie_scolaire/vosattentes.js
server/api/sections/sections.json

**Constat:**
- La dernière question du formulaire **"Vie scolaire ou étudiante" : *"Vous avez d'autres renseignements importants [...] ici :"* **et la réponse associée ne s'affichent pas dans le PDF récapitulatif.
*(Mantis 0007043)*
- La dernière question du formulaire **"Vie au travail" : *"Autres renseignements concernant [...] communiquer"* **et la réponse associée ne s'affichent pas dans le PDF récapitulatif.
*(Mantis 0007044)*
**Attendu :** 
Ces questions et leurs réponses doivent apparaître dans le CERFA (à la fin du questionnaire correspondant)

[Lot3.2_RecettePasse2] ETQ bénéficiaire, des réponses n'apparaissent pas dans le CERFA

---

client/components/detail/precisez_date_et_detail.html

Recette passe2 (20/03) - Mantis 0007049:
Ajouter un espace entre l'icône et le message

[Lot3.2_bug] - ETQ usager je souhaiterais un message d'erreur associé a chaque date du formulaire "Situations particulières"

---

client/app/dashboard/workflow/detail/detail.html
client/app/dashboard/workflow/list/list.controller.js
client/app/dashboard/workflow/list/list.html
client/app/gestion/demande/gestion.demande.controller.js
client/app/gestion/demande/gestion.demande.html
client/app/gestion/profil/gestion.profil.controller.js
client/components/banettes/banettes.constant.js
client/components/request/request.progress.component.js
documentation_fonctionnelle.md
server/api/request/request.controller.js
server/api/request/request.model.js
server/api/send-mail/templates/specific-content/reception-request-content.html
server/api/stats/stats.controller.js

modification BDD
modification tableau de bord

[Lot 4] N°16 - Tableau de bord - L'etat enregistré devient validé et l'etat archivé devient irrecevable

---

client/app/dashboard/workflow/list/list.controller.js
client/app/layout/layout.controller.js
client/app/layout/layout.html
client/components/menu-dashboard/menu-dashboard.component.js
client/components/menu-dashboard/menu-dashboard.html

*EBE 38, 39, 41, 47, 55*
**Attendu : Pour chacun des tableaux de bords agent des demandes : *émises / en attente / validées / irrecevables*.**
- Le clic sur « Retour au flux des demandes » renvoie vers le dernier onglet consulté (et non vers le premier onglet de la page)

[Lot 4] N°29 - Tableau de bord - Retour au flux des demandes

---

client/app/dashboard/list.scss
client/app/dashboard/workflow/detail/detail.controller.js
client/app/dashboard/workflow/detail/detail.html
client/app/dashboard/workflow/detail/detail.js
client/app/dashboard/workflow/detail/modalDelete.html
client/app/dashboard/workflow/list/list.controller.js
client/app/dashboard/workflow/list/list.html
client/app/dashboard/workflow/list/list.js
client/app/dashboard/workflow/workflow.controller.js
client/app/dashboard/workflow/workflow.js
client/index.html

*EBE :
- Demande validée : p.43 (via tableau de bord), 49 (détail demande) 
- Demande irrecevable : p.51 (via tableau de bord), 57 (détail demande)*
**Pour une demande à l'état validée ou irrecevable, depuis le tableau de bord des demandes : **
- Ajout de la colonne de suppression  : pour chaque demande un lien Supprimer est disponible de manière conditionnelle (Cf. carte 18 pour la condition)
- Le clic sur le bouton « Supprimer » fait apparaître la pop-in de suppression de la demande concernée. Dans cette pop-in:
- Le clic sur le bouton " Annuler " fait disparaître la pop-in
- Le clic sur le bouton "Supprimer" : supprime la demande 
**Pour une demande à l'état validée ou irrecevable, dans le détail de la demande :**
- Le clic sur le bouton « Supprimer » fait apparaître la pop-in de …

[Lot 4] N°19 - Tableau de bord - Supprimer la demande dans le tableau de bord

---

client/app/account/account.scss
client/app/account/signup/signup.controller.js
client/app/account/signup/signup.controller.spec.js
client/app/account/signup/signup.html

Revert "[Lot 4] N°35 - Sécurité - Utiliser un système de capcha pour securiser la creation d'un utilisateur"

---

client/app/account/account.js
client/app/account/signup/signup.controller.js
client/app/account/signup/signup.controller.spec.js
client/app/account/signup/signup.html
client/app/dashboard/users/agents/edit.html
client/components/password-field/password-field.component.js
client/components/password-field/password-field.html

renforcer la sécurité de la page d'inscription en utilisant le composant créé dans la PR 30. 
rendre la position et le libellé de ce composant paramétrable.

[Lot 4] N°31 - Sécurité - Amélioration de la page d’inscription - branche a partir de la branche 'lot4_30_tdb_gestion_mdp_compte_agent'

---

client/app/dashboard/users/agents/edit.html
client/app/mon_compte/mon_compte.controller.js
client/app/mon_compte/mon_compte.html
client/app/mon_compte/mon_compte.js
client/components/password-field/password-field.html

utiliser les composants créés dans la PR 30 et 31

[Lot 4] N°32 - Sécurité - Amélioration de la page de modification du mot de passe utilisateur

---

client/app/account/account.js
client/app/account/reset_password/resest_password.controller.js
client/app/account/reset_password/reset_password.html
client/app/account/signup/signup.html
client/app/dashboard/users/agents/edit.html
client/app/mon_compte/mon_compte.controller.js
client/app/mon_compte/mon_compte.html
client/components/password-field/password-field.component.js
client/components/password-field/password-field.html

utiliser les composants créés dans la PR 30 et 31

[Lot 4] N°33 - Sécurité - Amélioration de la page de reinitialisation du mot de passe utilisateur

---

server/api/sections/sections.json

Constat :
"As-t-il/elle déjà identifié une ou plusieurs structures qui pourraient répondre à ses attentes ?"
Attendu :
"A-t-il/elle déjà identifié une ou plusieurs structures qui pourraient répondre à ses attentes ?"

[Lot 3.2_RecettePasse2] Mantis 7052 ETQ bénéficiaire -20 ans, dans le formulaire Vie de votre aidant familial : faute d'orthographe

---

client/components/detail/independant.html

Remplacer le 'proprietaire' par Propriétaire et 'locataire' par Locataire

[Lot 3.2_qualifInternePasse2] Bug d'affichage des réponses dans le CERFA - Mantis 7027 sous-réponse non explicite

---

server/api/sections/sections.json

**Constat :**
Dans le CERFA  : "Vous disposez actuellement d'une aide humaine aux élèves handicapésune aide humaine aux élèves handicapés"
24/04 : même constat dans le formulaire
**Attendu : **
"Vous disposez actuellement d'une aide humaine aux élèves handicapés"
sur le formulaire et le CERFA PDF

[Recette_Lot anos 3.2_bug] libellé question CERFA Vie scolaire

---

client/app/gestion/demande/gestion.demande.html
client/app/gestion/profil/gestion.profil.html
client/app/main/main.html

-remplacer "Un suivi en ligne de votre dossier" par "Votre demande en ligne à la MDPH"

[Lot 4] N°41 - Général - Modification de la page d'accueil pour l'usager

---

client/components/auth/auth.service.js

Pour l'agent il manque le lien tableau de bord dans le menu, ainsi, une fois sur la page mon compte il n'y a pas la possibilité de retourner sur le tableau de bord

[pré-recette lot 4] : le lien tableau de bord manquant dans le menu

---

client/app/dashboard/workflow/list/list.js
client/app/dashboard/workflow/workflow.controller.js
client/components/resources/request.resource.js
server/api/mdph/mdph.controller.js
server/api/request/index.js
server/api/request/request.controller.js
server/api/request/request.model.js

précision à implémenter : 
le demandeur ne peut supprimer qu'une demande à l'état "en cours"; l'agent peut "supprimer" les autres demandes (après téléchargement) mais uniquement les infos utiles seront supprimées et la date de suppression sera renseignée, l'agent ne les verra plus mais le demandeur les verra dans ses demandes archivées.

[Lot 4] N°19 complément - Tableau de bord - Supprimer la demande dans le tableau de bord

---

client/app/dashboard/workflow/detail/modalDelete.html

Fonctionnement OK, design KO :
La popup de suppression est disproportionnée en hauteur par rapport au texte (ce n'est pas une suppression en masse).

[Lot 4_bugfix1] N°19 - Tableau de bord - Supprimer la demande dans le tableau de bord

---

client/app/dashboard/workflow/list/list.controller.js

Constat:au clic sur télécharger les demandes (avec des demandes cochées) rien ne se produit.

[Lot 4_bugfix1] N°21 - Tableau de bord - Telecharger en masse

---

client/app/dashboard/workflow/detail/detail.html

Constat: Il manque le titre "Demande irrecevable"

[Lot 4_bugfix1] N°24 - Tableau de bord - Modifier la page de detail d'une demande

---

client/app/layout/layout.html

-Faute d'orthographe : il manque le 's' à Profils dans le menu

[Lot 4_bugfix1] N°08 - Profil et demandes - Ajouter le menu "profil et demandes"

---

client/app/account/signup/signup.controller.js
client/app/account/signup/signup.controller.spec.js
server/api/user/user.controller.js

premier clic sur le bouton = rien se semble se passer,
deuxième clic sur le bouton = message d'erreur indiquant que le login est déjà inscrit

[Lot 4_bugfix2] N°31 - Sécurité - Amélioration de la page d’inscription

---

client/app/gestion/demande/gestion.demande.html
client/app/gestion/gestion.scss
client/app/gestion/profil/gestion.profil.html
client/app/layout/layout.controller.js
client/app/layout/layout.html
client/app/layout/layout.scss

suggestions d'amélioration pendant le rétrécissement de la fenêtre
-Menu : aérer le menu en agrandissant les espaces entre les lignes + le logo reste à sa place
-Fil d'ariane Profils>Demandes : lorsque le bloc passe sous l'icône Profils (Cf. PJ Recette_PlacementFilAriane), le fil d'ariane passe de suite au dessus de l'icône (le déplacement tardif de ce dernier rend le rétrécissement moins harmonieux)
-Adaptation des lignes du tableau : adapter la hauteur de toute la ligne (inclus les boutons de fin de ligne) pour éviter les cassures (Cf. PJ Recette_Profils_boutonSuppressionSur1ligne + Recette_Profils_adaptation des lignes)
-Transition du bouton Retour aux profils + fil d'ariane désolidarisé (Cf. PJ Recette_EcrasementBoutonsRetourFilAriane) : éviter ces écrasements, les boutons doivent …

[Lot 4_bugfix1] N°40 - Général - Creation d'un menu responsive

---

server/api/sections/sections.json

Les questions 
- "Vous avez indiqué recevoir une aide technique, matérielle, ou de l'équipement, cette aide consiste en :" (A)
et 
- "Vous avez indiqué recevoir une aide à la personne, vous êtes aidé.e par :" (B)
sont placées, dans le PDF récapitulatif, entre les questions "Dans les 12 mois précédant votre demande, avez vous perçu :" et "Vous percevez une ou plusieurs des aides suivantes :"
Elles doivent être placées dans cet ordre (A - B) entre la question "Connaissez vous votre taux d'IPP (Incapacité Permanante Partielle) ?" et la question : 
- "Êtes-vous à la retraite ?" (s'il s'agit d'un bénéficiaire de plus de 20 ans)
- "Du fait du handicap de [Prénom Bénéficaire] :" (s'il s'agit d'un bénéficiaire de moins de 20 ans)

[Ano lot3.2 - Mantis 7088] [Usager - PDF récapitulatif] Vie quotidienne - Ordre d'affichage

---

server/api/sections/sections.json

Ajouter ":" à la fin du titre de la question tel que : 
"Votre niveau de qualification :"

[Ano lot3.2 - Mantis 7099]  [Usager - PDF récapitulatif] Vie au travail - Question "Votre niveau de qualification"

---

server/api/sections/sections.json

Ajouter ":" à la fin du titre de la question tel que :
"Date de naissance :"

[Ano lot3.2 - Mantis 7102]  [Usager - PDF récapitulatif et Formulaire] Vie de votre aidant familial - Question "Date de naissance"

---

server/api/sections/sections.json

Constaté le 14/05/2018
Ajouter ":" à la fin du titre de la question tel que :
"Adresse :"

[Ano lot3.2 - Mantis 7103] [Usager - PDF récapitulatif et Formulaire] Vie de votre aidant familial - Question "Adresse"

---

server/api/sections/sections.json

Dans le titre de la dernière question du formulaire "Vie scolaire ou étudiante", ajouter un espace entre "Importants" et la parenthèse. Cela doit être fait sur le formulaire enfant, adulte et sur le PDF récapitulatif.

[Ano lot3.2 - Mantis 7090] [Usager - PDF récapitulatif et formulaire] Vie scolaire ou étudiante - Question Autres renseignements

---

server/api/sections/sections.json
server/components/recapitulatif.js

Lorsque la date est saisie, le PDF indique : 
"* Oui
° 11/11/1111"
Il faudrait ajouter "Depuis le" avant la date, tel que : 
"* Oui
° Depuis le 11/11/1111"

[Ano lot3.2 - Mantis 7089] [Usager - PDF Récapitulatif] Vie quotidienne > 20 ans - Question "Êtes-vous à la retraite ?"

---

server/api/sections/sections.json
server/components/recapitulatif.js

Lorsque la date est saisie, le PDF indique : 
"* Oui
° 11/11/1111"
Il faudrait ajouter "Le" avant la date, tel que : 
"* Oui
° Le 11/11/1111"

[Ano lot3.2 - Mantis 7096] "[Usager - PDF récapitulatif] Vie au travail - Question "Avez-vous rencontré un professionnel du service social ... "

---

client/app/dashboard/workflow/list/list.html
client/app/gestion/profil/gestion.profil.html

Plusieurs anomalies graphiques détectées sur la page de gestion des profils bénéficiaires, lorsque l'on est connecté en tant qu'usager :
1. la colonne de droite qui sert à l'affichage de l’icône profil, occupe 11% de l'écran, merci de retirer l'élément style de la div et laisser une largeur définie par bootstrap : col-md-2
2. de même retirer la définition de largeur sur le corps de la page et utiliser les largeurs définies par défaut : col-md-10
3. serait-il possible d'aligner verticalement et horizontalement l’icône des profils ?
Des anomalies sur les libellés de la page ont également été notées :
1. le libellé du bouton "Créer un nouveau profil *" doit comprendre un astérisque renvoyant à la note en italique, merci de …

[RC lot4 - Mantis 7142 - P1] ][Profil][Demande]: ajustement graphique.

---

client/app/demande/prestations/prestations.controller.js

Connecté en tant qu'usager, il est impossible de valider le formulaire "Expression des demandes de droits et prestations".

[Ano lot4 - Mantis 7131 - P0] [Usager][Saisie demande - Prestations] : Impossible de valider le formulaire

---

server/components/recapitulatif.js

Lorsque l'usager ne saisit aucun établissement, le PDF récapitulatif affiche "Etablissements", il faudrait qu'il affiche "Pas de réponse".
Attention, cette question est présente dans deux chemins différents sur le formulaire.

[Ano lot3.2 - Mantis 7093] [Usager - PDF récapitulatif] Vie scolaire ou étudiante - Questions "Dans quel(s) établissement(s) ?"

---

server/components/recapitulatif.js

Lorsque l'usager ne saisit aucun diplôme, le PDF récapitulatif affiche "Diplômes", il faudrait qu'il affiche "Pas de réponse".

[Ano lot3.2 - Mantis 7100] [Usager - PDF récapitulatif] Vie au travail - Question "Précisez votre/vos dernier(s) diplôme(s) obtenu(s) :"

---

client/app/account/confirmer_mail/confirmer_mail.html
client/app/account/signup/signup.html
client/app/mon_compte/mon_compte.html
client/components/password-field/password-field.html
client/components/password-rules-alert/password-rules-alert.html

revoir les messages sur les pages d'inscription, de création d'un compte agent, "mon compte" pour un utilisateur connecté, et page de réinitialisation du mot de passe.

Lot4 mantis7140 messages d'erreur concernant le mdp

---

client/components/question/pourcentageinput.html
client/components/question/question.controller.js

IE ne gere pas le type number des inputs

La saisie est bien contrôlée sur chrome, mais il est toujours possible de faire figurer du texte sous IE.

---

client/app/demande/demande-preview-modal.html

Connecté en tant qu'usager, au moment d'envoyer la demande, les éléments de langage de la pop-in de prévisualisation ne sont pas bons.
1. la phrase introductive de la pop-in n'est pas la bonne. Merci de placer le texte demandé dans l'expression de besoin (veillez au respect de la ponctuation et de l'accentuation) :
"Une fois la demande validée, vous ne pourrez plus modifier d'autres informations que les documents, et ce sur demande de la MDPH. Vous pourrez trouver ci-dessous le récapitulatif de votre demande :"
2. la phase de fin requiert un point et sa taille police soit être supérieure (au moins égale à celle utilisée pour les boutons) :
"En validant, je certifie que les informations ci-dessus sont exactes."

[RC lot4 - mantis 7151 - P2] [Usager][Pop-In Visualisation] : Révision des éléments de langage

---

client/components/question/frais_handicap.scss

Sous IE, on constate deux fleches pour le bonton du choix de la fréquence des frais.

[Ano lot 3.2 - Mantis 7084] [Usager - Vie quotidienne] Question "Frais liés au restant à charge"

---

client/app/gestion/profil/gestion.profil.controller.js
client/app/gestion/profil/gestion.profil.html

l'affichage de l'état de la demande lorsque le profil n'a aucune demande est "Dernière demande indéfinie"
=> ca doit etre un champs vide ""

[Lot 4_bugfix2] N°13 - Profil et demandes - Supprimer une demande

---

client/components/detail/precisez_date_et_detail.html

Ligne générale à suivre (vu avec le client le 07/06 cf mail) : Majuscule en début de phrase + point final

[Ano lot3.2 - Mantis 7049] [Usager - Formulaire] Situations particuliaires - Orthographe du message d'erreur
